[package]
name = "ScallopProtocol"
version = "0.0.1"
published-at = "0x38fe42a5a69f7eb3635404389e8003be9457b1a5c873f133184648c7e9bd47b7"

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
rev = "testnet"

[dependencies.Math]
local = "../libs/math"

[dependencies.X]
local = "../libs/x"

[dependencies.Whitelist]
local = "../libs/whitelist"

[dependencies.CoinDecimalsRegistry]
local = "../libs/coin_decimals_registry"

[dependencies.XOracle]
local = "../sui_x_oracle/x_oracle"

[addresses]
protocol = "0xefe8b36d5b2e43728cc323298626b83177803521d195cfb11e15b910e892fddf"
